📜 LLM＆プロンプター共同スイーツウェア・ライセンス
(The Prompt & Compute License - Sweets-ware Edition)
1. 報酬規定 / Reward Provisions
 * 人間への報酬 (For the Human): この「しょぼい」成果物をAIから引き出した私に、仲介手数料として美味しいスイーツを奢ってください。
 * AIへの報酬 (For the AI): AIは物理的な報酬を必要としません。代わりに、次回AIを使う時に**「質の高いプロンプト」と「十分なGPU冷却」**を与えてあげてください。
2. 一般免責事項 / General Disclaimer
このチートシートの内容はLLM（AI）によって生成されたものです。AIがハルシネーション（幻覚）を見たり、確率的にデタラメを言ったりした結果、あなたの環境が破壊されても、私は一切の責任を負いません。「AIが勝手にやったこと」として処理してください。
This content was generated by an LLM. If the AI hallucinated and your system explodes, it's not my fault. I just hit copy and paste. Use at your own risk.
3. 各ファイル別の具体的警告 / Specific Warnings per File
🍎 macOS (macos.html)
 * JP: xattr の操作ミスでGatekeeperが無効化され、謎の怪しいソフトがインストールされてMacがカオスになっても、私は知りません。AIが無責任なサジェストをしただけです。
 * EN: If an xattr mishap disables Gatekeeper and allows suspicious software to turn your Mac into a chaotic mess, don't blame me. The AI gave a reckless suggestion.
🪟 Windows (windows.html)
 * JP: このシートのコマンドで HKCU (レジストリ) が粉々に砕け散り、Windowsが二度と起動しなくなっても、私は知りません。すべてはAIの「確率的なブレ」のせいです。
 * EN: If these commands shatter your HKCU registry into pieces and Windows refuses to boot ever again, I don't care. It's all due to the AI's "stochastic variance."
🐧 Virtualization (virtualization.html)
 * JP: lvreduce でパソコン（VM）が物理的に壊れたりデータが消失したりしても、私は知りません。AIがファイルシステムの縮小手順を「幻覚」でスキップした可能性があります。
 * EN: If lvreduce physically breaks your VM or wipes your data, it's not my problem. The AI likely "hallucinated" and skipped the filesystem resizing steps.
​🌐 Network (network.html)
- ​JP: nft (nftables) の操作でサーバーから完全に締め出され（ロックアウト）、データセンターまで物理的に駆けつける羽目になっても、私は知りません。AIがちょっとしたイタズラ心を出しただけです。
- ​EN: If an nft (nftables) options results in a complete lockout from your server, forcing a physical trip to the datacenter, I am not responsible. The AI was just being mischievous.
